# Generated by Django 3.2.25 on 2024-04-23 08:09
from django.db import migrations
import django.db.models.deletion
import parler.fields
class Migration(migrations.Migration):
    dependencies = [
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.article'),
        ),
        migrations.AlterField(
            model_name='newsblogconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.newsblogconfig'),
        ),
    ]
