# Generated by Django 5.2.3 on 2025-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0021_remove_articletranslation_master_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlecontenttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterField(
            model_name='articlecontenttranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the URL. If changed, the URL will change. Clear it to have it re-created automatically.', max_length=255, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecontenttranslation',
            unique_together={('language_code', 'master'), ('language_code', 'master', 'slug')},
        ),
    ]
